### ISSUE TITLE
[Scholarships Page] Fix page heading to match Figma

### ISSUE THREAD

**Issue by shiinasugioka** [Seattle-HIMA/shima-website#60]
Intended Design:

![image](https://github.com/Seattle-HIMA/shima-website/assets/91639423/2f20c7a1-9395-4a98-9289-d735f281be64)

Current Design (page design is not dynamic to page width):
![image](https://github.com/Seattle-HIMA/shima-website/assets/91639423/ba39b9bc-853a-49c0-8b01-c6489a2b0837)

**Comment by Allison-Ho** [comment]
done
